language: objective-c
osx_image: xcode9.4
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=SFProgressCircle.xcworkspace
  - FRAMEWORK_SCHEME="SFProgressCircle"
  - EXAMPLE_SCHEME="Example"
  - IOS_SDK=iphonesimulator11.4
  - DESTINATION="name=iPhone 8,OS=11.4"
script:
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace "$WORKSPACE" -scheme "$FRAMEWORK_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO clean build | xcpretty -c
  - xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO clean build | xcpretty -c
